name: Create a comment on new issues
permissions: 
  issues: write
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
              **NICE ISSUE BUDDY** \n :) 
          reactions: '+1'